// LOCALHOST 
### GET all contacts
GET http://localhost:8080/contacts

### GET contacts by id
GET http://localhost:8080/contacts/63d3580f7d1c9765da57b1da
###
GET http://localhost:8080/contacts/63d358267d1c9765da57e6b8
###
GET http://localhost:8080/contacts/63d358447d1c9765da582bc3

### Create contact
POST http://localhost:8080/contacts HTTP/1.1 
content-type: application/json

{
"firstName":"Elizabeth", 
"lastName":"Tellez", 
"email":"elizabethtellez@gmail.com", 
"favoriteColor":"Blue", 
"birthday":"03/18/1995"
}

### Put contact
PUT http://localhost:8080/contacts/63d481afc2c3daeddd03886a HTTP/1.1 
content-type: application/json

{
"firstName":"Beth", 
"lastName":"Tellez", 
"email":"bethtellez@gmail.com", 
"favoriteColor":"Blue", 
"birthday":"03/18/1995"
}

### DELETE contact
DELETE http://localhost:8080/contacts/63d4661e685ee670b46a86aa HTTP/1.1

// PRODUCTION Deploy
#### 
GET https://cse341-tellez-week04.onrender.com/contacts

#### Get contacts by id
GET https://cse341-tellez-week04.onrender.com/contacts/63d3580f7d1c9765da57b1da
#### 
GET https://cse341-tellez-week04.onrender.com/contacts/63d358267d1c9765da57e6b8
#### 
GET https://cse341-tellez-week04.onrender.com/contacts/63d358447d1c9765da582bc3

### Create contact
POST https://cse341-tellez-week04.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
"firstName": "Elizabeth", 
"lastName": "Tellez", 
"email": "elizabethtellez@gmail.com", 
"favoriteColor": "Blue", 
"birthday": "03/18/95"
}

### PUT contact
PUT https://cse341-tellez-week04.onrender.com/contacts/63d46681ab42f3d4c598cc4a HTTP/1.1 
content-type: application/json

{
"firstName": "Beth", 
"lastName": "Tellez", 
"email": "bethtellez@gmail.com", 
"favoriteColor": "Blue", 
"birthday": "03/18/95"
}

### DELETE contact
DELETE https://cse341-tellez-week04.onrender.com/contacts/63d46681ab42f3d4c598cc4a HTTP/1.1

